# Generated by Django 3.2.12 on 2023-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doing',
            field=models.BooleanField(default=False),
        ),
    ]
